/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as AiImport } from './routes/ai'
import { Route as AppRouteImport } from './routes/_app/route'
import { Route as IndexImport } from './routes/index'
import { Route as AppWorkspaceIssuesImport } from './routes/_app/$workspace/issues'
import { Route as AppWorkspaceInboxImport } from './routes/_app/$workspace/inbox'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AiRoute = AiImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRoute,
} as any)

const AppRouteRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppWorkspaceIssuesRoute = AppWorkspaceIssuesImport.update({
  id: '/$workspace/issues',
  path: '/$workspace/issues',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppWorkspaceInboxRoute = AppWorkspaceInboxImport.update({
  id: '/$workspace/inbox',
  path: '/$workspace/inbox',
  getParentRoute: () => AppRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_app/$workspace/inbox': {
      id: '/_app/$workspace/inbox'
      path: '/$workspace/inbox'
      fullPath: '/$workspace/inbox'
      preLoaderRoute: typeof AppWorkspaceInboxImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/$workspace/issues': {
      id: '/_app/$workspace/issues'
      path: '/$workspace/issues'
      fullPath: '/$workspace/issues'
      preLoaderRoute: typeof AppWorkspaceIssuesImport
      parentRoute: typeof AppRouteImport
    }
  }
}

// Create and export the route tree

interface AppRouteRouteChildren {
  AppWorkspaceInboxRoute: typeof AppWorkspaceInboxRoute
  AppWorkspaceIssuesRoute: typeof AppWorkspaceIssuesRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppWorkspaceInboxRoute: AppWorkspaceInboxRoute,
  AppWorkspaceIssuesRoute: AppWorkspaceIssuesRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppRouteRouteWithChildren
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/$workspace/inbox': typeof AppWorkspaceInboxRoute
  '/$workspace/issues': typeof AppWorkspaceIssuesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppRouteRouteWithChildren
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/$workspace/inbox': typeof AppWorkspaceInboxRoute
  '/$workspace/issues': typeof AppWorkspaceIssuesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/_app/$workspace/inbox': typeof AppWorkspaceInboxRoute
  '/_app/$workspace/issues': typeof AppWorkspaceIssuesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/ai'
    | '/dashboard'
    | '/login'
    | '/$workspace/inbox'
    | '/$workspace/issues'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/ai'
    | '/dashboard'
    | '/login'
    | '/$workspace/inbox'
    | '/$workspace/issues'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/ai'
    | '/dashboard'
    | '/login'
    | '/_app/$workspace/inbox'
    | '/_app/$workspace/issues'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AiRoute: typeof AiRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AiRoute: AiRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/ai",
        "/dashboard",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app/route.tsx",
      "children": [
        "/_app/$workspace/inbox",
        "/_app/$workspace/issues"
      ]
    },
    "/ai": {
      "filePath": "ai.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_app/$workspace/inbox": {
      "filePath": "_app/$workspace/inbox.tsx",
      "parent": "/_app"
    },
    "/_app/$workspace/issues": {
      "filePath": "_app/$workspace/issues.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
